/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTracesRouteImport } from './routes/_authed/traces'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMemoryRouteImport } from './routes/_authed/memory'
import { Route as AuthedLocksRouteImport } from './routes/_authed/locks'
import { Route as AuthedHealthRouteImport } from './routes/_authed/health'
import { Route as AuthedDlqRouteImport } from './routes/_authed/dlq'
import { Route as AuthedCostsRouteImport } from './routes/_authed/costs'
import { Route as AuthedWorkflowsIndexRouteImport } from './routes/_authed/workflows/index'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedAgentsIndexRouteImport } from './routes/_authed/agents/index'
import { Route as AuthedWorkflowsWorkflowIdRouteImport } from './routes/_authed/workflows/$workflowId'
import { Route as AuthedTasksTaskIdRouteImport } from './routes/_authed/tasks/$taskId'
import { Route as AuthedAgentsAgentIdRouteImport } from './routes/_authed/agents/$agentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTracesRoute = AuthedTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMemoryRoute = AuthedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocksRoute = AuthedLocksRouteImport.update({
  id: '/locks',
  path: '/locks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHealthRoute = AuthedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDlqRoute = AuthedDlqRouteImport.update({
  id: '/dlq',
  path: '/dlq',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCostsRoute = AuthedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsIndexRoute = AuthedWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsIndexRoute = AuthedAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdRoute =
  AuthedWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTasksTaskIdRoute = AuthedTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsAgentIdRoute = AuthedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/costs': typeof AuthedCostsRoute
  '/dlq': typeof AuthedDlqRoute
  '/health': typeof AuthedHealthRoute
  '/locks': typeof AuthedLocksRoute
  '/memory': typeof AuthedMemoryRoute
  '/settings': typeof AuthedSettingsRoute
  '/traces': typeof AuthedTracesRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRoute
  '/agents/': typeof AuthedAgentsIndexRoute
  '/tasks/': typeof AuthedTasksIndexRoute
  '/workflows/': typeof AuthedWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/costs': typeof AuthedCostsRoute
  '/dlq': typeof AuthedDlqRoute
  '/health': typeof AuthedHealthRoute
  '/locks': typeof AuthedLocksRoute
  '/memory': typeof AuthedMemoryRoute
  '/settings': typeof AuthedSettingsRoute
  '/traces': typeof AuthedTracesRoute
  '/': typeof AuthedIndexRoute
  '/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRoute
  '/agents': typeof AuthedAgentsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
  '/workflows': typeof AuthedWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/costs': typeof AuthedCostsRoute
  '/_authed/dlq': typeof AuthedDlqRoute
  '/_authed/health': typeof AuthedHealthRoute
  '/_authed/locks': typeof AuthedLocksRoute
  '/_authed/memory': typeof AuthedMemoryRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/traces': typeof AuthedTracesRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/agents/$agentId': typeof AuthedAgentsAgentIdRoute
  '/_authed/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/_authed/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRoute
  '/_authed/agents/': typeof AuthedAgentsIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
  '/_authed/workflows/': typeof AuthedWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/costs'
    | '/dlq'
    | '/health'
    | '/locks'
    | '/memory'
    | '/settings'
    | '/traces'
    | '/agents/$agentId'
    | '/tasks/$taskId'
    | '/workflows/$workflowId'
    | '/agents/'
    | '/tasks/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/costs'
    | '/dlq'
    | '/health'
    | '/locks'
    | '/memory'
    | '/settings'
    | '/traces'
    | '/'
    | '/agents/$agentId'
    | '/tasks/$taskId'
    | '/workflows/$workflowId'
    | '/agents'
    | '/tasks'
    | '/workflows'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/costs'
    | '/_authed/dlq'
    | '/_authed/health'
    | '/_authed/locks'
    | '/_authed/memory'
    | '/_authed/settings'
    | '/_authed/traces'
    | '/_authed/'
    | '/_authed/agents/$agentId'
    | '/_authed/tasks/$taskId'
    | '/_authed/workflows/$workflowId'
    | '/_authed/agents/'
    | '/_authed/tasks/'
    | '/_authed/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/traces': {
      id: '/_authed/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof AuthedTracesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/memory': {
      id: '/_authed/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthedMemoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locks': {
      id: '/_authed/locks'
      path: '/locks'
      fullPath: '/locks'
      preLoaderRoute: typeof AuthedLocksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/health': {
      id: '/_authed/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthedHealthRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dlq': {
      id: '/_authed/dlq'
      path: '/dlq'
      fullPath: '/dlq'
      preLoaderRoute: typeof AuthedDlqRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/costs': {
      id: '/_authed/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthedCostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/': {
      id: '/_authed/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthedWorkflowsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/': {
      id: '/_authed/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAgentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId': {
      id: '/_authed/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId': {
      id: '/_authed/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthedTasksTaskIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents/$agentId': {
      id: '/_authed/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthedAgentsAgentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCostsRoute: typeof AuthedCostsRoute
  AuthedDlqRoute: typeof AuthedDlqRoute
  AuthedHealthRoute: typeof AuthedHealthRoute
  AuthedLocksRoute: typeof AuthedLocksRoute
  AuthedMemoryRoute: typeof AuthedMemoryRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTracesRoute: typeof AuthedTracesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAgentsAgentIdRoute: typeof AuthedAgentsAgentIdRoute
  AuthedTasksTaskIdRoute: typeof AuthedTasksTaskIdRoute
  AuthedWorkflowsWorkflowIdRoute: typeof AuthedWorkflowsWorkflowIdRoute
  AuthedAgentsIndexRoute: typeof AuthedAgentsIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
  AuthedWorkflowsIndexRoute: typeof AuthedWorkflowsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCostsRoute: AuthedCostsRoute,
  AuthedDlqRoute: AuthedDlqRoute,
  AuthedHealthRoute: AuthedHealthRoute,
  AuthedLocksRoute: AuthedLocksRoute,
  AuthedMemoryRoute: AuthedMemoryRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTracesRoute: AuthedTracesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAgentsAgentIdRoute: AuthedAgentsAgentIdRoute,
  AuthedTasksTaskIdRoute: AuthedTasksTaskIdRoute,
  AuthedWorkflowsWorkflowIdRoute: AuthedWorkflowsWorkflowIdRoute,
  AuthedAgentsIndexRoute: AuthedAgentsIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
  AuthedWorkflowsIndexRoute: AuthedWorkflowsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
